language: csharp
solution: RDFSharp.sln
install:
  - nuget restore RDFSharp.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release RDFSharp.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./DemoApp/bin/Debug/RDFSharp.dll